import Head from "next/head";

import { Resources } from "@/components/resources/Resources";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-xl mx-auto py-12 md:max-w-4xl">
        <h1 className="font-title text-5xl">Faker Snippets</h1>
        <hr className="my-10" />
        <Resources />
      </main>
    </>
  );
}
